apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-cloudbuild
  template:
    metadata:
      labels:
        app: hello-cloudbuild
    spec:
      containers:
      - name: hello-cloudbuild
        image: gcr.io/qwiklabs-gcp-01-5bb0bc288382/sample-app:v1.0
        ports:
        - containerPort: 8080
